UCall.UI/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Highsoft.Web.Mvc.Charts;
using UCall.Application;
using UCall.UI.Models;

namespace UCall.UI.Controllers
{
    public class DashboardController : UCallController
    {
        private static CampanhaApp _campanhaApp;
        private static ChamadasApp _chamadasApp;

        public DashboardController()
        {
            _campanhaApp = new CampanhaApp();
            _chamadasApp = new ChamadasApp();
        }
        // GET: Dashboard
        public ActionResult Index()
        {
            var fechatemp = DateTime.Now;

            var modelo = new DashboardViewModel
            {
                Campanha = 1,
                //DataInicio = new DateTime(fechatemp.Year, fechatemp.Month, 1),
                //DataFim = new DateTime(fechatemp.Year, fechatemp.Month, DateTime.DaysInMonth(fechatemp.Year, fechatemp.Month))

                DataInicio = new DateTime(2017,1,1),
                DataFim = new DateTime(2017,1,31)
            };

            modelo.DataFim = modelo.DataFim.AddDays(1).AddSeconds(-1);

            var pieData = new List<PieSeriesData>();

            var aaa = _chamadasApp.Top5ChamadasCompletas(modelo.DataInicio, modelo.DataFim, modelo.Campanha);

            foreach (var tipo in aaa)
            {
                pieData.Add(new PieSeriesData { Name = tipo.Key, Y = tipo.Value });
            }

            pieData[0].Sliced = true;
            pieData[0].Selected = true;
            
            ViewData["pieData"] = pieData;

            ViewData["Recebidas"] = _chamadasApp.ChamadasRecebidas(modelo.DataInicio, modelo.DataFim, modelo.Campanha);

            ViewData["Atendidas"] = _chamadasApp.ChamadasAtendidas(modelo.DataInicio, modelo.DataFim, modelo.Campanha);
            /*
            List<double?> johnValues = new List<double?> { 5, 3, 4, 7, 2 };
            List<double?> janeValues = new List<double?> { 2, 2, 3, 2, 1 };
            List<double?> joeValues = new List<double?> { 3, 4, 4, 2, 5 };

            List<ColumnSeriesData> johnData = new List<ColumnSeriesData>();
            List<ColumnSeriesData> janeData = new List<ColumnSeriesData>();
            List<ColumnSeriesData> joeData = new List<ColumnSeriesData>();

            johnValues.ForEach(p => johnData.Add(new ColumnSeriesData { Y = p }));
            janeValues.ForEach(p => janeData.Add(new ColumnSeriesData { Y = p }));
            joeValues.ForEach(p => joeData.Add(new ColumnSeriesData { Y = p }));

            ViewData["johnData"] = johnData;
            ViewData["janeData"] = janeData;
            ViewData["joeData"] = joeData;*/

            EnviarCampanhas(modelo.Campanha);

            return View(modelo);
        }

        [HttpPost]
        public ActionResult Index(DashboardViewModel modelo)
        {

            EnviarCampanhas(modelo.Campanha);
            return View(modelo);
        }

        private void EnviarCampanhas(int? idCampanha)
        {
            var campanhas = _campanhaApp.ListarCampanhas();
            ViewBag.IdCampanha = new SelectList(campanhas, "key", "value", idCampanha);
        }
    }
}

UCall.UI/Controllers/ServiceLevelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Highsoft.Web.Mvc.Charts;
using Microsoft.Ajax.Utilities;
using UCall.Application;
using UCall.UI.Models;

namespace UCall.UI.Controllers
{
    public class ServiceLevelController : UCallController
    {
        
        private static CampanhaApp _campanhaApp;
        private static ChamadasApp _chamadasApp;

        public ServiceLevelController()
        {
            _campanhaApp = new CampanhaApp();
            _chamadasApp = new ChamadasApp();
        }

        public ActionResult Relatorio()
        {
            EnviarCampanhas(null);
            ViewBag.Resumos = new List<ResumoHora>();
            return View();
        }

        [HttpPost]
        public ActionResult Relatorio(RelatorioViewModel relatorio)
        {
            EnviarCampanhas(relatorio.IdCampanha);

            ViewBag.Resumos = _chamadasApp.RelatorioDiario(relatorio.Data, relatorio.IdCampanha);

            return View(relatorio);
        }


        public ActionResult Graficos()
        {
            EnviarCampanhas(null);
            return View();
        }

        [HttpPost]
        public ActionResult Graficos(RelatorioViewModel relatorio)
        {
            EnviarCampanhas(relatorio.IdCampanha);
            var resumos = _chamadasApp.RelatorioDiario(relatorio.Data, relatorio.IdCampanha);

            List<LineSeriesData> total = new List<LineSeriesData>();
            List<LineSeriesData> atendidas = new List<LineSeriesData>();
            List<LineSeriesData> abandonadas = new List<LineSeriesData>();
            List<LineSeriesData> rejectadas = new List<LineSeriesData>();
            List<LineSeriesData> rona = new List<LineSeriesData>();
            List<LineSeriesData> sobrecargas = new List<LineSeriesData>();

            resumos.Select(x => x.Chamadas).ForEach(x => { total.Add(new LineSeriesData { Y = x }); });
            resumos.Select(x => x.AtendidasLower + x.AtendidasUpper ).ForEach(x => { atendidas.Add(new LineSeriesData { Y = x }); });
            resumos.Select(x => x.AbandonadasLower + x.AbandonadasUpper).ForEach(x => { abandonadas.Add(new LineSeriesData { Y = x }); });
            resumos.Select(x => x.Rejectadas).ForEach(x => { rejectadas.Add(new LineSeriesData { Y = x }); });
            resumos.Select(x => x.Rona).ForEach(x => { rona.Add(new LineSeriesData { Y = x }); });
            resumos.Select(x => x.Sobrecargas).ForEach(x => { sobrecargas.Add(new LineSeriesData { Y = x }); });

            ViewData["total"] = total;
            ViewData["atendidas"] = atendidas;
            ViewData["abandonadas"] = abandonadas;
            ViewData["rejectadas"] = rejectadas;
            ViewData["rona"] = rona;
            ViewData["sobrecargas"] = sobrecargas;

            return View(relatorio);
        }

        private void EnviarCampanhas(int? idCampanha)
        {
            var campanhas = _campanhaApp.ListarCampanhas();
            ViewBag.IdCampanha = new SelectList(campanhas,"key","value",idCampanha);
        }
    }
}

UCall.UI/Views/Shared/LayOut.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewBag.Title</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    <link href="~/assets/plugins/PleaseWait/please-wait.css" rel="stylesheet" />
    <script src="~/assets/plugins/PleaseWait/please-wait.js"></script>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<!-- ADD THE CLASS fixed TO GET A FIXED HEADER AND SIDEBAR LAYOUT -->
<!-- the fixed layout is not compatible with sidebar-mini -->
<body class="hold-transition skin-purple sidebar-collapse sidebar-mini">
    <script type="text/javascript">
        function Splash() {
            var splash = window.pleaseWait({
                logo: "/assets/img/logoweb.png",
                backgroundColor: '#3c8dbc',
                loadingHtml: '<div class="sk-folding-cube"><div class="sk-cube1 sk-cube" ></div><div class="sk-cube2 sk-cube"></div><div class="sk-cube4 sk-cube"></div><div class="sk-cube3 sk-cube"></div></div>'
            });

            return splash;
        }

        waiter = Splash();
        $(document)
            .ready(function () {
                setTimeout(function () {
                    waiter.finish();
                }, 2000);

            });
    </script>
    <!-- Site wrapper -->
    <div class="wrapper">
        <header class="main-header">
            <!-- Logo -->
            <a href="#" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini"><b>U</b>Call</span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg"><b>U</b>Call DashBoard</span>
            </a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        @*@if (User.Identity.IsAuthenticated)
                        {
                            @Html.Partial("Profile", usuario)
                        }*@
                    </ul>
                </div>
            </nav>
        </header>
        <!-- =============================================== -->
        <aside class="main-sidebar">

            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- Sidebar Menu -->
                <ul class="sidebar-menu">
                    @Html.Partial("Menus")
                </ul>
                <!-- /.sidebar-menu -->
            </section>
            <!-- /.sidebar -->
        </aside>
        <!-- =============================================== -->
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <h1>
                    @ViewBag.Title
                    <small>@ViewBag.Subtitle</small>
                </h1>

            </section>
            <!-- Main content -->
            <section class="content">
                @RenderBody()
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <footer class="main-footer">
            <div class="pull-right hidden-xs">
                <b>Version</b> @ViewContext.Controller.GetType().Assembly.GetName().Version
            </div>
            <strong>Copyright &copy; @DateTime.Now.Year <a href="https://www.facebook.com/erikson.gomes">Erikson Melgarejo</a>.</strong>
        </footer>
    </div>

    <!-- ./wrapper -->
    <link href="~/assets/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/assets/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/assets/css/AdminLTE.min.css" rel="stylesheet" />
    @*<link href="~/assets/css/skins/skin-blue.min.css" rel="stylesheet" />*@
    <link href="~/assets/css/skins/skin-purple.min.css" rel="stylesheet" />
    <link href="~/assets/plugins/iCheck/flat/blue.css" rel="stylesheet" />
    <link href="~/assets/plugins/SweetAlert2/sweetalert2.css" rel="stylesheet" />
    <link href="~/assets/plugins/datatables/jquery.dataTables.min.css" rel="stylesheet" />
    <link href="~/assets/plugins/datatables/dataTables.bootstrap.css" rel="stylesheet" />

    <script src="~/assets/js/bootstrap.js"></script>
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/assets/plugins/slimScroll/jquery.slimscroll.min.js"></script>
    <script src="~/assets/plugins/fastclick/fastclick.min.js"></script>
    <script src="~/assets/js/app.min.js"></script>
    <script src="~/assets/js/demo.js"></script>
    <script src="~/assets/plugins/SweetAlert2/sweetalert2.min.js"></script>
    <script src="~/assets/js/AdminLTE.js"></script>
    <script src="~/assets/plugins/iCheck/icheck.min.js"></script>

    <script src="~/assets/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/assets/plugins/datatables/dataTables.bootstrap.min.js"></script>

<script src="~/assets/js/EriksonJS.js"></script>
    
    
    <script src="~/assets/plugins/HighCharts/highcharts.js"></script>
<script src="~/assets/plugins/HighCharts/highcharts-3d.js"></script>
    <script src="~/assets/plugins/HighCharts/modules/exporting.js"></script>

<script>
        $(document).ready(function () {
            $('input[type="radio"]')
                .iCheck({
                    checkboxClass: 'icheckbox_flat-blue',
                    radioClass: 'iradio_flat-blue',
                    increaseArea: '20%' // optional
                });

            $('input[type="checkbox"]:not(.bootstrap-switch)')
                .iCheck({
                    checkboxClass: 'icheckbox_flat-blue',
                    radioClass: 'iradio_flat-blue',
                    increaseArea: '20%' // optional
                });

            $('.tabela').ToTable();
        })
    </script>

    @RenderSection("scripts", required: false)

    @{
        if (ViewBag.Erro != null)
        {
            foreach (var m in (List<string>)ViewBag.Erro)
            {
                <script>
                    MsgErro('@m');
                </script>
            }
        }

        if (TempData["Ok"] != null)
        {
            foreach (var m in (List<string>)TempData["Ok"])
            {
                <script>
                    MsgOk('@m');
                </script>
            }
        }

        if (ViewBag.Info != null)
        {
            foreach (var m in (List<string>)ViewBag.Info)
            {
                <script>
                    MsgInfo('@m');
                </script>
            }
        }

        if (ViewBag.Alerta != null)
        {
            foreach (var m in (List<string>)ViewBag.Alerta)
            {
                <script>
                    MsgAlerta('@m');
                </script>
            }
        }

    }
</body>
</html>

UCall.UI/Views/Shared/Menus.cshtml
@*<section class="sidebar">
    <ul class="sidebar-menu">
        <li class="header">Menu de Navegação</li>
        <li>
            <a href="@(Url.Action("Index","Home"))">
                <i class="fa fa-home fa-fw"></i> <span>Inicio</span>
            </a>
        </li>
        
    </ul>
</section>*@
<li class="header">Menu de Navegação</li>
<li><a href="@(Url.Action("Index","Home"))"><i class="fa fa-home"></i> <span>Inicio</span></a></li>
@*<li><a href="@(Url.Action("Index","ServiceLevel"))"><i class="fa fa-calendar"></i> <span>Metricas Diarias</span></a></li>*@
<li class="treeview">
    <a href="#">
        <i class="fa fa-calendar fa-fw"></i>
        <span>Metricas Diarias</span>
        <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
        </span>
    </a>
    <ul class="treeview-menu">
        <li><a href="@(Url.Action("Relatorio","ServiceLevel"))"><i class="fa fa-file"></i> Relatorio</a></li>
        <li><a href="@(Url.Action("Graficos","ServiceLevel"))"><i class="fa fa-line-chart"></i> Graficos</a></li>
    </ul>
</li>
<li><a href="@(Url.Action("Index","Dashboard"))"><i class="fa fa-dashboard"></i> <span>Dashboard</span></a></li>
@*
     <li>
        <a href="@(Url.Action("","",new{ Area = ""}))">
            <i class="fa fa-th fa-fw"></i> <span>Widgets</span>
        </a>
    </li>

    <li>
        <a href="@(Url.Action("","",new{ Area = ""}))">
            <i class="fa fa-th fa-fw"></i> <span>Widgets</span>
            <span class="pull-right-container">
                <small class="label pull-right bg-green">new</small>
            </span>
        </a>
    </li>

    <li class="treeview">
        <a href="#">
            <i class="fa fa-files-o fa-fw"></i>
            <span>Layout Options</span>
    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
        </a>
        <ul class="treeview-menu">
            <li><a href="@(Url.Action("","",new{ Area = ""}))"><i class="fa fa-circle-o"></i> Top Navigation</a></li>
        </ul>
    </li>

    <li class="treeview">
            <a href="#">
                <i class="fa fa-share"></i> <span>Multilevel</span>
                <span class="pull-right-container">
                    <i class="fa fa-angle-left pull-right"></i>
                </span>
            </a>
            <ul class="treeview-menu">
                <li><a href="#"><i class="fa fa-circle-o"></i> Level One</a></li>
                <li>
                    <a href="#">
                        <i class="fa fa-circle-o"></i> Level One
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li><a href="#"><i class="fa fa-circle-o"></i> Level Two</a></li>
                        <li>
                            <a href="#">
                                <i class="fa fa-circle-o"></i> Level Two
                                <span class="pull-right-container">
                                    <i class="fa fa-angle-left pull-right"></i>
                                </span>
                            </a>
                            <ul class="treeview-menu">
                                <li><a href="#"><i class="fa fa-circle-o"></i> Level Three</a></li>
                                <li><a href="#"><i class="fa fa-circle-o"></i> Level Three</a></li>
                            </ul>
                        </li>
                    </ul>
                </li>
                <li><a href="#"><i class="fa fa-circle-o"></i> Level One</a></li>
            </ul>
        </li>
*@

UCall.UI/Views/Shared/Profile.cshtml
@model Modelo.AspNetUsers

<li class="dropdown user user-menu">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <img src="@Model.PicPath" class="user-image" alt="User Image">
        <span class="hidden-xs">@Model.Nome</span>
    </a>
    <ul class="dropdown-menu">
        <!-- User image -->
        <li class="user-header">
            <img src="@Model.PicPath" class="img-circle" alt="User Image">
            <p>
                @Model.Nome
                <small>@Model.Email</small>
            </p>
        </li>
        <!-- Menu Body -->
        @*<li class="user-body">
            <div class="row">
                <div class="col-xs-4 text-center">
                    <a href="#">Followers</a>
                </div>
                <div class="col-xs-4 text-center">
                    <a href="#">Sales</a>
                </div>
                <div class="col-xs-4 text-center">
                    <a href="#">Friends</a>
                </div>
            </div>
        </li>*@
        <!-- Menu Footer-->
        <li class="user-footer">
            <div class="pull-left">
                <a href="#" class="btn btn-default btn-flat"><i class="fa fa-user"></i>&nbsp;Perfil</a>
            </div>
            <div class="pull-right">
                @using (Html.BeginForm("LogOff", "Conta",new{Area =""}))
                {
                    @Html.AntiForgeryToken()
                    <button class="btn btn-default btn-flat" type="submit"><i class="fa fa-sign-out"></i>&nbsp;Sair</button>
                }
               
            </div>
        </li>
    </ul>
</li>